### ISSUE TITLE
13-36的解法有误

### ISSUE THREAD

**Issue by xush6528** [white0rchardpUnK/Cpp-Primer-5th-Solutions#1]
```
Message::Message(const Message &m) :
    contents(m.contents), folders(m.folders){
    add_to_Folders(m);          //将本消息添加到指向m的Folder中
}

void Message::add_to_Folders(const Message &m) {
    for (auto f : m.folders)    //对每个包含m的Folder
        f->addMsg(this);        //向该Folder添加一个指向本Message的指针
}

```
message.folders已经被拷贝过了。`folders(m.folders)`。

```
void Folder::addMsg(Message *m) {
    m->folders.insert(this);
}
```
Folder那边再让`m->folder.insert()`一次是重复操作。Debug的方法应该是assert insert成功。

题目的意思应该是Folder会维护一个`std:set<Message*>`。

可以参考，https://github.com/jaege/Cpp-Primer-5th-Exercises/blob/master/ch13/13.36.cpp。

**Comment by white0rchardpUnK** [comment]
看了一下，问题出在隐式形参this，应该是写的时候晕了习惯性的写了this
已更正，感谢指出

**Comment by xush6528** [comment]
void Folder::remMsg(Message *m) 也需要更新。
