### ISSUE TITLE
13.28题解有误

### ISSUE THREAD

**Issue by rhcher** [white0rchardpUnK/Cpp-Primer-5th-Solutions#5]
```c++
inline TreeNode::TreeNode(const TreeNode& t)
    : value(t.value), count(t.count), left(new TreeNode(*t.left)), right(new TreeNode(*t.right) { }
```
这里没有判断指针是否为空，拷贝初始化的时候会将空指针解引用

**Comment by white0rchardpUnK** [comment]
Thanks for your feedback, the official source code is what I recommend you to check.
You can review it [here](https://github.com/white0rchardpUnK/Cpp-Primer-5th-Solutions/tree/master/data/GCC_pre_C11/13).
