### ISSUE TITLE
16.62 题解有误

### ISSUE THREAD

**Issue by floatval** [white0rchardpUnK/Cpp-Primer-5th-Solutions#6]
Sala data 类缺失了一个 friend bool operator==(const sal&l, const sal& r)
因为无序的关联容器,默认使用的是相应类型的 == 进行排序

**Comment by white0rchardpUnK** [comment]
Thanks for your feedback, the official source code here is what I recommend you to check.
If you are still a little confused, please refer to my latest official solution.
[Sales_data.h.txt](https://github.com/white0rchardpUnK/Cpp-Primer-5th-Solutions/files/7609563/Sales_data.h.txt)
[Sales_data.c.txt](https://github.com/white0rchardpUnK/Cpp-Primer-5th-Solutions/files/7609569/Sales_data.c.txt)
